# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tasarım2.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(668, 456)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 621, 391))
        self.groupBox.setObjectName("groupBox")
        self.lbl_sonuc = QtWidgets.QLabel(self.groupBox)
        self.lbl_sonuc.setGeometry(QtCore.QRect(30, 300, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lbl_sonuc.setFont(font)
        self.lbl_sonuc.setObjectName("lbl_sonuc")
        self.btnCevir = QtWidgets.QPushButton(self.groupBox)
        self.btnCevir.setGeometry(QtCore.QRect(280, 170, 291, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btnCevir.setFont(font)
        self.btnCevir.setObjectName("btnCevir")
        self.input = QtWidgets.QLineEdit(self.groupBox)
        self.input.setGeometry(QtCore.QRect(30, 53, 541, 91))
        self.input.setObjectName("input")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 140, 241, 159))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.rbBuyut = QtWidgets.QRadioButton(self.layoutWidget)
        self.rbBuyut.setObjectName("rbBuyut")
        self.verticalLayout.addWidget(self.rbBuyut)
        self.rbKucuk = QtWidgets.QRadioButton(self.layoutWidget)
        self.rbKucuk.setObjectName("rbKucuk")
        self.verticalLayout.addWidget(self.rbKucuk)
        self.rbCumleBasHarf = QtWidgets.QRadioButton(self.layoutWidget)
        self.rbCumleBasHarf.setObjectName("rbCumleBasHarf")
        self.verticalLayout.addWidget(self.rbCumleBasHarf)
        self.rbKelimeBasHarf = QtWidgets.QRadioButton(self.layoutWidget)
        self.rbKelimeBasHarf.setObjectName("rbKelimeBasHarf")
        self.verticalLayout.addWidget(self.rbKelimeBasHarf)
        self.output = QtWidgets.QTextBrowser(self.groupBox)
        self.output.setGeometry(QtCore.QRect(155, 310, 391, 71))
        self.output.setObjectName("output")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 668, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.lbl_sonuc.setText(_translate("MainWindow", "SONUÇ : "))
        self.btnCevir.setText(_translate("MainWindow", "ÇEVİR"))
        self.rbBuyut.setText(_translate("MainWindow", "BÜYÜT"))
        self.rbKucuk.setText(_translate("MainWindow", "KÜÇÜLT"))
        self.rbCumleBasHarf.setText(_translate("MainWindow", "CÜMLE BAŞ HARFİİNİ BÜYÜT"))
        self.rbKelimeBasHarf.setText(_translate("MainWindow", "HER KELİMENİN BAŞ HARFİNİ BÜYÜT"))
